// <auto-generated />
using System;
using BaseOOPDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaseOOPDAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190430093034_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaseOOPDAL.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Designer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("EffectivenessCoefficient");

                    b.Property<int>("Experience");

                    b.Property<string>("FirstName");

                    b.Property<int?>("ManagerId");

                    b.Property<decimal>("Salary");

                    b.Property<string>("SecondName");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Designers");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Experience");

                    b.Property<string>("FirstName");

                    b.Property<int?>("ManagerId");

                    b.Property<decimal>("Salary");

                    b.Property<string>("SecondName");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DepartmentId");

                    b.Property<int>("Experience");

                    b.Property<string>("FirstName");

                    b.Property<int?>("ManagerId");

                    b.Property<decimal>("Salary");

                    b.Property<string>("SecondName");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Designer", b =>
                {
                    b.HasOne("BaseOOPDAL.Entities.Manager", "Manager")
                        .WithMany("DesignersTeam")
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Developer", b =>
                {
                    b.HasOne("BaseOOPDAL.Entities.Manager", "Manager")
                        .WithMany("DevelopersTeam")
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Manager", b =>
                {
                    b.HasOne("BaseOOPDAL.Entities.Department", "Department")
                        .WithMany("Managers")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("BaseOOPDAL.Entities.Manager", "Manager")
                        .WithMany("ManagersTeam")
                        .HasForeignKey("ManagerId");
                });
#pragma warning restore 612, 618
        }
    }
}
