// <auto-generated />
using System;
using BaseOOPDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaseOOPDAL.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190430105427_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaseOOPDAL.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("Experience");

                    b.Property<string>("FirstName");

                    b.Property<int?>("ManagerId");

                    b.Property<decimal>("Salary");

                    b.Property<string>("SecondName");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Designer", b =>
                {
                    b.HasBaseType("BaseOOPDAL.Entities.Employee");

                    b.Property<decimal>("EffectivenessCoefficient");

                    b.HasDiscriminator().HasValue("Designer");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Developer", b =>
                {
                    b.HasBaseType("BaseOOPDAL.Entities.Employee");

                    b.HasDiscriminator().HasValue("Developer");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Manager", b =>
                {
                    b.HasBaseType("BaseOOPDAL.Entities.Employee");

                    b.Property<int?>("DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Employee", b =>
                {
                    b.HasOne("BaseOOPDAL.Entities.Manager", "Manager")
                        .WithMany("Team")
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("BaseOOPDAL.Entities.Manager", b =>
                {
                    b.HasOne("BaseOOPDAL.Entities.Department", "Department")
                        .WithMany("Managers")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
